### ISSUE TITLE
Resistor on Q1

### ISSUE THREAD

**Issue by Circuitsoft** [tpmanley/dogcage#4]
The TIP120 has a B-E voltage drop of 2.5v max, and an hFE around 2500 at a 4A load. Having the transistor directly connected to the pin on the teensy could be potentially damaging to the I/O pin. A 470 ohm resistor will provide almost 2mA, which should be plenty to saturate the TIP120. I would also recommend a bulk filter capacitor (100uF or so) across power to the servo to make sure current draw pulses don't cause random resets in the controllers.

**Comment by tpmanley** [comment]
Thanks for the review Alex! You made great points and I updated the schematic.
